# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-08 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('Mail', models.CharField(max_length=100)),
                ('Wishes', models.CharField(max_length=400)),
            ],
        ),
    ]
